// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & {
    // Group
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & {
    // Other fields
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutPageDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutPageDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titolo della pagina per social e motori di ricerca
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Breve descrizione della pagina
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

/**
 * Item in *Appartamento → Galleria*
 */
export interface ApartmentDocumentDataGalleryItem {
  /**
   * Immagine field in *Appartamento → Galleria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Appartamento documents
 */
interface ApartmentDocumentData {
  /**
   * Nome field in *Appartamento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome dell'appartamento
   * - **API ID Path**: apartment.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Località field in *Appartamento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Roma, Trastevere
   * - **API ID Path**: apartment.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Descrizione field in *Appartamento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrizione dell'appartamento
   * - **API ID Path**: apartment.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Immagine di copertina field in *Appartamento*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Galleria field in *Appartamento*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<ApartmentDocumentDataGalleryItem>>;

  /**
   * Numero camere field in *Appartamento*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.rooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rooms: prismic.NumberField;

  /**
   * Ospiti max field in *Appartamento*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.guests
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  guests: prismic.NumberField;

  /**
   * Link prenotazione field in *Appartamento*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.booking_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  booking_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * Meta Title field in *Appartamento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Appartamento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Appartamento*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: apartment.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Appartamento document from Prismic
 *
 * - **API ID**: `apartment`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ApartmentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ApartmentDocumentData>,
    "apartment",
    Lang
  >;

/**
 * Content for FAQ Item documents
 */
interface FaqItemDocumentData {
  /**
   * Domanda field in *FAQ Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_item.question
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Risposta field in *FAQ Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_item.answer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;

  /**
   * Categoria field in *FAQ Item*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: generale
   * - **API ID Path**: faq_item.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "proprietario" | "hosting" | "generale",
    "filled"
  >;
}

/**
 * FAQ Item document from Prismic
 *
 * - **API ID**: `faq_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FaqItemDocumentData>,
    "faq_item",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | HeroSlice
  | EvocativePhraseSlice
  | CategoryShowcaseSlice
  | AboutTeaserSlice
  | TestimonialsSlice
  | ContattiSlice;

/**
 * Content for Home documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titolo della pagina per social e motori di ricerca
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Breve descrizione della pagina
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type HostingPageDocumentDataSlicesSlice = never;

/**
 * Content for Hosting documents
 */
interface HostingPageDocumentData {
  /**
   * Slice Zone field in *Hosting*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hosting_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HostingPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Hosting*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titolo della pagina per social e motori di ricerca
   * - **API ID Path**: hosting_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Hosting*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Breve descrizione della pagina
   * - **API ID Path**: hosting_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hosting*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hosting_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Hosting document from Prismic
 *
 * - **API ID**: `hosting_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HostingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HostingPageDocumentData>,
    "hosting_page",
    Lang
  >;

type PropertyManagerPageDocumentDataSlicesSlice = never;

/**
 * Content for Property Manager documents
 */
interface PropertyManagerPageDocumentData {
  /**
   * Slice Zone field in *Property Manager*
   *
   * - **Field Type**: Slice Zone
   * - **API ID Path**: academy_page.slices[]
   * - **Tab**: Main
   */
  slices: prismic.SliceZone<PropertyManagerPageDocumentDataSlicesSlice>;

  /**
   * Meta Title field in *Property Manager*
   *
   * - **API ID Path**: academy_page.meta_title
   * - **Tab**: SEO & Metadata
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Property Manager*
   *
   * - **API ID Path**: academy_page.meta_description
   * - **Tab**: SEO & Metadata
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Property Manager*
   *
   * - **API ID Path**: academy_page.meta_image
   * - **Tab**: SEO & Metadata
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Property Manager document from Prismic — the underlying Prismic type id stays
 * `academy_page` so existing content keeps rendering on the /property-manager URL.
 *
 * - **API ID**: `academy_page`
 * - **Repeatable**: `false`
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PropertyManagerPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PropertyManagerPageDocumentData>,
    "academy_page",
    Lang
  >;

type ProprietarioPageDocumentDataSlicesSlice = never;

/**
 * Content for Proprietario documents
 */
interface ProprietarioPageDocumentData {
  /**
   * Slice Zone field in *Proprietario*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: proprietario_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProprietarioPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Proprietario*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titolo della pagina per social e motori di ricerca
   * - **API ID Path**: proprietario_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Proprietario*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Breve descrizione della pagina
   * - **API ID Path**: proprietario_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Proprietario*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: proprietario_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Proprietario document from Prismic
 *
 * - **API ID**: `proprietario_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProprietarioPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProprietarioPageDocumentData>,
    "proprietario_page",
    Lang
  >;

/**
 * Content for Membro del Team documents
 */
interface TeamMemberDocumentData {
  /**
   * Nome field in *Membro del Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Ruolo field in *Membro del Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Foto field in *Membro del Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  photo: prismic.ImageField<never>;

  /**
   * Bio field in *Membro del Team*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * È founder? field in *Membro del Team*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: team_member.is_founder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_founder: prismic.BooleanField;
}

/**
 * Membro del Team document from Prismic
 *
 * - **API ID**: `team_member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamMemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TeamMemberDocumentData>,
    "team_member",
    Lang
  >;

/**
 * Content for Testimonianza documents
 */
interface TestimonialDocumentData {
  /**
   * Nome field in *Testimonianza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome dell'autore
   * - **API ID Path**: testimonial.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Ruolo / Profilo field in *Testimonianza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Es. Proprietario, Ospite, Host
   * - **API ID Path**: testimonial.author_role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_role: prismic.KeyTextField;

  /**
   * Foto field in *Testimonianza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.author_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Quote field in *Testimonianza*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Testo della testimonianza
   * - **API ID Path**: testimonial.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Categoria field in *Testimonianza*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ospite
   * - **API ID Path**: testimonial.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<"proprietario" | "ospite" | "host", "filled">;
}

/**
 * Testimonianza document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | ApartmentDocument
  | FaqItemDocument
  | HomePageDocument
  | HostingPageDocument
  | ProprietarioPageDocument
  | PropertyManagerPageDocument
  | TeamMemberDocument
  | TestimonialDocument;

/**
 * Primary content in *AboutTeaser → Default → Primary*
 */
export interface AboutTeaserSliceDefaultPrimary {
  /**
   * Eyebrow field in *AboutTeaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Chi siamo
   * - **API ID Path**: about_teaser.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Titolo field in *AboutTeaser → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet.
   * - **API ID Path**: about_teaser.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Paragrafo (opzionale) field in *AboutTeaser → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_teaser.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * Immagine field in *AboutTeaser → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_teaser.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Testo CTA field in *AboutTeaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Conosciamoci
   * - **API ID Path**: about_teaser.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Link CTA field in *AboutTeaser → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_teaser.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for AboutTeaser Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutTeaserSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTeaserSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutTeaser*
 */
type AboutTeaserSliceVariation = AboutTeaserSliceDefault;

/**
 * AboutTeaser Shared Slice
 *
 * - **API ID**: `about_teaser`
 * - **Description**: Anteprima sezione 'Chi siamo' con immagine grande e CTA.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutTeaserSlice = prismic.SharedSlice<
  "about_teaser",
  AboutTeaserSliceVariation
>;

/**
 * Item in *CategoryShowcase → Default → Primary → Card*
 */
export interface CategoryShowcaseSliceDefaultPrimaryCardsItem {
  /**
   * Eyebrow field in *CategoryShowcase → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hai un immobile?
   * - **API ID Path**: category_showcase.default.primary.cards[].eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Titolo field in *CategoryShowcase → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_showcase.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Immagine field in *CategoryShowcase → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_showcase.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *CategoryShowcase → Default → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category_showcase.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Testo CTA field in *CategoryShowcase → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Scopri di più
   * - **API ID Path**: category_showcase.default.primary.cards[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Colore di sfondo card field in *CategoryShowcase → Default → Primary → Card*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: category_showcase.default.primary.cards[].background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Primary content in *CategoryShowcase → Default → Primary*
 */
export interface CategoryShowcaseSliceDefaultPrimary {
  /**
   * Card field in *CategoryShowcase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category_showcase.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<CategoryShowcaseSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for CategoryShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategoryShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoryShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CategoryShowcase*
 */
type CategoryShowcaseSliceVariation = CategoryShowcaseSliceDefault;

/**
 * CategoryShowcase Shared Slice
 *
 * - **API ID**: `category_showcase`
 * - **Description**: Sezione con scroll orizzontale a card (Proprietari / Host / Consulenze).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategoryShowcaseSlice = prismic.SharedSlice<
  "category_showcase",
  CategoryShowcaseSliceVariation
>;

/**
 * Item in *Contatti → Default → Primary → Social*
 */
export interface ContattiSliceDefaultPrimarySocialsItem {
  /**
   * Piattaforma field in *Contatti → Default → Primary → Social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: instagram
   * - **API ID Path**: contatti.default.primary.socials[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    "instagram" | "facebook" | "linkedin" | "tiktok",
    "filled"
  >;

  /**
   * URL field in *Contatti → Default → Primary → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti.default.primary.socials[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Contatti → Default → Primary*
 */
export interface ContattiSliceDefaultPrimary {
  /**
   * Titolo field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hai delle domande da farci?
   * - **API ID Path**: contatti.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Sottotitolo field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lascia i tuoi contatti per essere ricontattato.
   * - **API ID Path**: contatti.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Mostra form field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contatti.default.primary.show_form
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_form: prismic.BooleanField;

  /**
   * Testo bottone invio field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Invia
   * - **API ID Path**: contatti.default.primary.submit_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_label: prismic.KeyTextField;

  /**
   * Email field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 7sundays@7sundays.it
   * - **API ID Path**: contatti.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Telefono field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +39 393 004 7956
   * - **API ID Path**: contatti.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Social field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials: prismic.GroupField<Simplify<ContattiSliceDefaultPrimarySocialsItem>>;
}

/**
 * Default variation for Contatti Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContattiSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContattiSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contatti*
 */
type ContattiSliceVariation = ContattiSliceDefault;

/**
 * Contatti Shared Slice
 *
 * - **API ID**: `contatti`
 * - **Description**: Sezione contatti generica con form opzionale + email/telefono/social.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContattiSlice = prismic.SharedSlice<
  "contatti",
  ContattiSliceVariation
>;

/**
 * Primary content in *EvocativePhrase → Default → Primary*
 */
export interface EvocativePhraseSliceDefaultPrimary {
  /**
   * Frase field in *EvocativePhrase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Every detail. Every stay. Every Sunday.
   * - **API ID Path**: evocative_phrase.default.primary.phrase
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  phrase: prismic.RichTextField;

  /**
   * Sottotitolo (opzionale) field in *EvocativePhrase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Milano curata in ogni dettaglio.
   * - **API ID Path**: evocative_phrase.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Sfondo field in *EvocativePhrase → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light
   * - **API ID Path**: evocative_phrase.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    "light" | "dark" | "primary" | "orange",
    "filled"
  >;
}

/**
 * Default variation for EvocativePhrase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EvocativePhraseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EvocativePhraseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EvocativePhrase*
 */
type EvocativePhraseSliceVariation = EvocativePhraseSliceDefault;

/**
 * EvocativePhrase Shared Slice
 *
 * - **API ID**: `evocative_phrase`
 * - **Description**: Banner full-width con una frase evocativa centrata.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EvocativePhraseSlice = prismic.SharedSlice<
  "evocative_phrase",
  EvocativePhraseSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → CTA*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Testo bottone field in *Hero → Default → Primary → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hai una proprietà
   * - **API ID Path**: hero.default.primary.buttons[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Link field in *Hero → Default → Primary → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].button_href
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_href: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Variante field in *Hero → Default → Primary → CTA*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: hero.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"primary" | "ghost", "filled">;
}

/**
 * Item in *Hero → Single CTA → Primary → CTA*
 */
export interface HeroSliceSingleCtaPrimaryButtonsItem {
  /**
   * Testo bottone field in *Hero → Single CTA → Primary → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.buttons[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Link field in *Hero → Single CTA → Primary → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.buttons[].button_href
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_href: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Variante field in *Hero → Single CTA → Primary → CTA*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: hero.singleCta.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"primary" | "ghost", "filled">;
}

/**
 * Item in *Hero → With Slider → Primary → CTA*
 */
export interface HeroSliceWithSliderPrimaryButtonsItem {
  /**
   * Testo bottone field in *Hero → With Slider → Primary → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.buttons[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Link field in *Hero → With Slider → Primary → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.buttons[].button_href
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_href: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Variante field in *Hero → With Slider → Primary → CTA*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: hero.withSlider.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"primary" | "ghost", "filled">;
}

/**
 * Item in *Hero → With Slider → Primary → Slider immagini*
 */
export interface HeroSliceWithSliderPrimarySliderImagesItem {
  /**
   * Immagine field in *Hero → With Slider → Primary → Slider immagini*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.slider_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titolo - riga 1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Everything, handled.
   * - **API ID Path**: hero.default.primary.title_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_1: prismic.KeyTextField;

  /**
   * Titolo - riga 2 (opzionale) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_2: prismic.KeyTextField;

  /**
   * Paragrafo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Thoughtful property management and curated stays in Milan.
   * - **API ID Path**: hero.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * Immagine di sfondo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero con due CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Single CTA → Primary*
 */
export interface HeroSliceSingleCtaPrimary {
  /**
   * Titolo - riga 1 field in *Hero → Single CTA → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.title_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_1: prismic.KeyTextField;

  /**
   * Titolo - riga 2 (opzionale) field in *Hero → Single CTA → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_2: prismic.KeyTextField;

  /**
   * Paragrafo field in *Hero → Single CTA → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * Immagine di sfondo field in *Hero → Single CTA → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * CTA field in *Hero → Single CTA → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.singleCta.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceSingleCtaPrimaryButtonsItem>>;
}

/**
 * Single CTA variation for Hero Slice
 *
 * - **API ID**: `singleCta`
 * - **Description**: Hero con una sola CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSingleCta = prismic.SharedSliceVariation<
  "singleCta",
  Simplify<HeroSliceSingleCtaPrimary>,
  never
>;

/**
 * Primary content in *Hero → With Slider → Primary*
 */
export interface HeroSliceWithSliderPrimary {
  /**
   * Titolo - riga 1 field in *Hero → With Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.title_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_1: prismic.KeyTextField;

  /**
   * Titolo - riga 2 (opzionale) field in *Hero → With Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_2: prismic.KeyTextField;

  /**
   * Paragrafo field in *Hero → With Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * Immagine fallback field in *Hero → With Slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * CTA field in *Hero → With Slider → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceWithSliderPrimaryButtonsItem>>;

  /**
   * Slider immagini field in *Hero → With Slider → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withSlider.primary.slider_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  slider_images: prismic.GroupField<
    Simplify<HeroSliceWithSliderPrimarySliderImagesItem>
  >;
}

/**
 * With Slider variation for Hero Slice
 *
 * - **API ID**: `withSlider`
 * - **Description**: Hero con slider di immagini
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceWithSlider = prismic.SharedSliceVariation<
  "withSlider",
  Simplify<HeroSliceWithSliderPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceSingleCta
  | HeroSliceWithSlider;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero full-bleed con titolo, paragrafo, CTA e immagine di sfondo. Variazioni: default (2 CTA), singleCta, withSlider.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Testimonials → Carousel → Primary → Testimonianze (manuali)*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Testimonianza field in *Testimonials → Carousel → Primary → Testimonianze (manuali)*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].testimonial_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  testimonial_link: prismic.ContentRelationshipField<"testimonial">;
}

/**
 * Primary content in *Testimonials → Carousel → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Titolo (opzionale) field in *Testimonials → Carousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Modalità field in *Testimonials → Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: carousel
   * - **API ID Path**: testimonials.default.primary.display_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  display_mode: prismic.SelectField<"carousel" | "grid", "filled">;

  /**
   * Categoria (auto-fetch, opzionale) field in *Testimonials → Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.filter_category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  filter_category: prismic.SelectField<"proprietario" | "ospite" | "host">;

  /**
   * Testimonianze (manuali) field in *Testimonials → Carousel → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Carousel variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Carousel di testimonianze
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Sezione testimonianze con carousel o griglia.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      ApartmentDocument,
      ApartmentDocumentData,
      ApartmentDocumentDataGalleryItem,
      FaqItemDocument,
      FaqItemDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      HostingPageDocument,
      HostingPageDocumentData,
      HostingPageDocumentDataSlicesSlice,
      ProprietarioPageDocument,
      ProprietarioPageDocumentData,
      ProprietarioPageDocumentDataSlicesSlice,
      TeamMemberDocument,
      TeamMemberDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      AboutTeaserSlice,
      AboutTeaserSliceDefaultPrimary,
      AboutTeaserSliceVariation,
      AboutTeaserSliceDefault,
      CategoryShowcaseSlice,
      CategoryShowcaseSliceDefaultPrimaryCardsItem,
      CategoryShowcaseSliceDefaultPrimary,
      CategoryShowcaseSliceVariation,
      CategoryShowcaseSliceDefault,
      ContattiSlice,
      ContattiSliceDefaultPrimarySocialsItem,
      ContattiSliceDefaultPrimary,
      ContattiSliceVariation,
      ContattiSliceDefault,
      EvocativePhraseSlice,
      EvocativePhraseSliceDefaultPrimary,
      EvocativePhraseSliceVariation,
      EvocativePhraseSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceSingleCtaPrimaryButtonsItem,
      HeroSliceSingleCtaPrimary,
      HeroSliceWithSliderPrimaryButtonsItem,
      HeroSliceWithSliderPrimarySliderImagesItem,
      HeroSliceWithSliderPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSingleCta,
      HeroSliceWithSlider,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
