// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  evocative_phrase: dynamic(() => import("./EvocativePhrase")),
  category_showcase: dynamic(() => import("./CategoryShowcase")),
  about_teaser: dynamic(() => import("./AboutTeaser")),
  testimonials: dynamic(() => import("./Testimonials")),
  contatti: dynamic(() => import("./Contatti")),
  gallery: dynamic(() => import("./Gallery")),
  founder_spotlight: dynamic(() => import("./FounderSpotlight")),
  team_photo: dynamic(() => import("./TeamPhoto")),
  process_steps: dynamic(() => import("./ProcessSteps")),
  faq: dynamic(() => import("./Faq")),
  image_highlights: dynamic(() => import("./ImageHighlights")),
  image_showcase: dynamic(() => import("./ImageShowcase")),
  services_showcase: dynamic(() => import("./ServicesShowcase")),
  learning_steps: dynamic(() => import("./LearningSteps")),
  benefits_grid: dynamic(() => import("./BenefitsGrid")),
};
