// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  evocative_phrase: dynamic(() => import("./EvocativePhrase")),
  category_showcase: dynamic(() => import("./CategoryShowcase")),
  about_teaser: dynamic(() => import("./AboutTeaser")),
  testimonials: dynamic(() => import("./Testimonials")),
  contatti: dynamic(() => import("./Contatti")),
};
